Spring models implementation
lkesko1/NWT_Tim17 pull request #2
Opened 2018-03-22 22:00 UTC by United4ever

2018-03-23 00:06 UTC, adkl requested changes

2018-03-23 00:06 UTC, adkl commented on nwt-cinema-movies/src/main/java/ba/unsa/etf/nwtcinemamovies/Models/UserRole.java
> +	@JoinColumn(name = "role_id")
Fali id

2018-03-23 00:06 UTC, adkl commented on nwt-cinema-projections/src/main/java/ba/unsa/etf/nwtcinemaprojections/Models/MovieTimetable.java
> +
Fali veza na film

2018-03-23 00:06 UTC, adkl commented on nwt-cinema-movies/src/main/java/ba/unsa/etf/nwtcinemamovies/Models/MovieReview.java
> +	@JoinColumn(name = "movie_id")
jesi siguran da se ovako pravi FK na drugu tabelu u istoj bazi?

2018-03-23 00:16 UTC, adkl commented
Ja ovo ne bih merge, dok se ili ne popravi skripta ili napisu repozitoriji i normalna seed metoda

2018-03-24 08:35 UTC, United4ever commented on nwt-cinema-movies/src/main/java/ba/unsa/etf/nwtcinemamovies/Models/MovieReview.java
> +	@JoinColumn(name = "movie_id")
Zaboravio sam staviti @ManyToOne

2018-03-24 09:39 UTC, United4ever commented
Popravio sam skriptu sad je sve ok, kreiraju se tabele, sve se seeda kako treba. Treba jos prepraviti ERD sa tvojim komentarima iznad.

2018-03-26 23:00 UTC, merged